services:
  rabbit:
    container_name: rabbit
    environment:
      RABBITMQ_DEFAULT_PASS: 1234
      RABBITMQ_DEFAULT_USER: admin
    image: rabbitmq:3.13-management
    ports:
    - 127.0.0.1:5672:5672
    - 127.0.0.1:15672:15672
